name: C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        cl /EHsc Maze_Solver\Main.cpp /Fe:Maze_Solver\MyProgram.exe

    - name: Run
      run: .\Maze_Solver\MyProgram.exe
